### ISSUE TITLE
作者为什么把Tortoise改成了SqlModel了，作者感觉Tortoise有什么缺点吗

### ISSUE THREAD

**Issue by zhaowanpeng** [cary997/fastcow-devops#1]

**Comment by cary997** [comment]
Tottoise orm是个很好用的orm ,但是自从v2版本以来bug频出修复缓慢， 我之前有给tortoise提过lssues https://github.com/tortoise/tortoise-orm/issues/1551 ，我觉得主要来自于他和pydantic v2兼容性的问题，我觉得即使他将目前的bug都修复完，后期pydantic发生大更新后他就还是会出现问题。所以我选择了兼容性更好的sqlmode，使用体验目前还不错。

**Comment by zhaowanpeng** [comment]
谢谢，解答

**Comment by cary997** [comment]
不客气
